# Generated by Django 4.2.4 on 2023-08-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstudents',
            old_name='profile_image',
            new_name='profile_pic',
        ),
    ]
