"""student_management_system URL Configuration"""
from django.conf.urls.static import static

from django.urls import path, include
from django.contrib import admin
from students_app import views, views_admin, views_staff, views_student
from students_app.view_edit_result import ViewEditResultClass
from student_management_system import settings

urlpatterns = [
    # General Views
    path('admin/', admin.site.urls),
    path('accounts/',include('django.contrib.auth.urls')),
    path('demo',views.show_demo_page),
    path('admin_signup',views.admin_signup,name="admin_signup"),
    path('student_signup',views.student_signup,name="student_signup"),
    path('staff_signup',views.staff_signup,name="staff_signup"),
    path('admin_signup_complete',views.admin_signup_complete,name="admin_signup_complete"),
    path('staff_signup_complete',views.staff_signup_complete,name="staff_signup_complete"),
    path('signup_student_complete',views.signup_student_complete,name="signup_student_complete"),
    path('',views.show_login_page,name="show_login"),
    path('get_user_details', views.get_user_details),
    path('user_logout', views.user_logout,name="logout"),
    path('do_login',views.do_login,name="do_login"),
    path('run_migrations/', views.run_migrations, name="run_migrations"),


    #Admin Views
    path('index',views_admin.index,name="index"),
    path('staff_entry',views_admin.staff_entry,name="staff_entry"),
    path('staff_entry_save',views_admin.staff_entry_save,name="staff_entry_save"),
    path('course_entry/', views_admin.course_entry,name="course_entry"),
    path('course_entry_save', views_admin.course_entry_save,name="course_entry_save"),
    path('student_entry', views_admin.student_entry,name="student_entry"),
    path('student_entry_save', views_admin.student_entry_save,name="student_entry_save"),
    path('subject_entry', views_admin.subject_entry,name="subject_entry"),
    path('subject_entry_save', views_admin.subject_entry_save,name="subject_entry_save"),
    path('staff_manage', views_admin.staff_manage,name="staff_manage"),
    path('student_manage', views_admin.student_manage,name="student_manage"),
    path('course_manage', views_admin.course_manage,name="course_manage"),
    path('subject_manage', views_admin.subject_manage,name="subject_manage"),
    path('staff_edit/<str:staff_id>', views_admin.staff_edit,name="staff_edit"),
    path('staff_edit_save', views_admin.staff_edit_save,name="staff_edit_save"),
    path('student_edit/<str:student_id>', views_admin.student_edit,name="student_edit"),
    path('student_edit_save', views_admin.student_edit_save,name="student_edit_save"),
    path('subject_edit/<str:subject_id>', views_admin.subject_edit,name="subject_edit"),
    path('subject_edit_save', views_admin.subject_edit_save,name="subject_edit_save"),
    path('course_edit/<str:course_id>', views_admin.course_edit,name="course_edit"),
    path('course_edit_save', views_admin.course_edit_save,name="course_edit_save"),
    path('session_manage', views_admin.session_manage,name="session_manage"),
    path('session_entry', views_admin.session_entry,name="session_entry"),
    path('session_delete/<int:session_id>/', views_admin.session_delete, name='session_delete'),
    path('session_add_save', views_admin.session_add_save,name="session_add_save"),
    path('email_is_exist', views_admin.email_is_exist,name="email_is_exist"),
    path('username_is_exist', views_admin.username_is_exist,name="username_is_exist"),
    path('feedback_student_admin',
         views_admin.feedback_student_admin,name="feedback_student_admin"),
    path('feedback_student_reply',
         views_admin.feedback_student_reply,name="feedback_student_reply"),
    path('feedback_staff_admin',
         views_admin.feedback_staff_admin,name="feedback_staff_admin"),
    path('feedback_staff_reply',
         views_admin.feedback_staff_reply,name="feedback_staff_reply"),
    path('view_leave_student', views_admin.view_leave_student,name="view_leave_student"),
    path('view_leave_staff', views_admin.view_leave_staff,name="view_leave_staff"),
    path('student_leave_approve/<str:leave_id>',
         views_admin.student_leave_approve,name="student_leave_approve"),
    path('student_leave_disapprove/<str:leave_id>',
         views_admin.student_leave_disapprove,name="student_leave_disapprove"),
    path('staff_leave_disapprove/<str:leave_id>',
         views_admin.staff_leave_disapprove,name="staff_leave_disapprove"),
    path('staff_leave_approve/<str:leave_id>',
         views_admin.staff_leave_approve,name="staff_leave_approve"),
    path('attendance_display_admin',
         views_admin.attendance_display_admin,name="attendance_display_admin"),
    path('get_dates_attendance',
         views_admin.get_dates_attendance,name="get_dates_attendance"),
    path('get_student_attendance',
         views_admin.get_student_attendance,name="get_student_attendance"),
    path('profile_admin', views_admin.profile_admin,name="profile_admin"),
    path('profile_admin_save', views_admin.profile_admin_save,name="profile_admin_save"),
    path('notification_send_staff_admin',
         views_admin.notification_send_staff_admin,name="notification_send_staff_admin"),
    path('notification_send_student_admin',
         views_admin.notification_send_student_admin,name="notification_send_student_admin"),
    path('send_notification_student',
         views_admin.send_notification_student,name="send_notification_student"),
    path('send_notification_staff',
         views_admin.send_notification_staff,name="send_notification_staff"),

    # Staff Views
    path('staff_index', views_staff.staff_index, name="staff_index"),
    path('take_attendance_staff', views_staff.take_attendance_staff, name="take_attendance_staff"),
    path('update_attendance_staff',
         views_staff.update_attendance_staff, name="update_attendance_staff"),
    path('students_fetch', views_staff.students_fetch, name="students_fetch"),
    path('attendance_get_dates', views_staff.attendance_get_dates, name="attendance_get_dates"),
    path('attendance_get_student',
         views_staff.attendance_get_student, name="attendance_get_student"),
    path('attendance_save_data',
         views_staff.attendance_save_data, name="attendance_save_data"),
    path('updateattendance_save_data',
         views_staff.updateattendance_save_data, name="updateattendance_save_data"),
    path('apply_leave_staff', views_staff.apply_leave_staff, name="apply_leave_staff"),
    path('apply_leave_staff_save',
         views_staff.apply_leave_staff_save, name="apply_leave_staff_save"),
    path('feedback_staff', views_staff.feedback_staff, name="feedback_staff"),
    path('feedback_staff_save', views_staff.feedback_staff_save, name="feedback_staff_save"),
    path('profile_staff', views_staff.profile_staff, name="profile_staff"),
    path('profile_staff_save', views_staff.profile_staff_save, name="profile_staff_save"),
    path('staff_fcmtoken_save', views_staff.staff_fcmtoken_save, name="staff_fcmtoken_save"),
    path('staff_all_notification',
         views_staff.staff_all_notification, name="staff_all_notification"),
    path('add_result_staff', views_staff.add_result_staff, name="add_result_staff"),
    path('save_student_result', views_staff.save_student_result, name="save_student_result"),
    path('student_edit_result',ViewEditResultClass.as_view(), name="student_edit_result"),
    path('fetch_result_student',views_staff.fetch_result_student, name="fetch_result_student"),
    path('live_video_conference',
         views_staff.live_video_conference, name="live_video_conference"),
    path('live_classroom_start_process',
         views_staff.live_classroom_start_process, name="live_classroom_start_process"),

     # Student Views
    path('student_index', views_student.student_index, name="student_index"),
    path('view_attendance_student',
         views_student.view_attendance_student, name="view_attendance_student"),
    path('view_attendance_student_post',
         views_student.view_attendance_student_post, name="view_attendance_student_post"),
    path('apply_leave_student', views_student.apply_leave_student, name="apply_leave_student"),
    path('apply_leave_student_save',
         views_student.apply_leave_student_save, name="apply_leave_student_save"),
    path('feedback_student', views_student.feedback_student, name="feedback_student"),
    path('feedback_student_save',
         views_student.feedback_student_save, name="feedback_student_save"),
    path('profile_student', views_student.profile_student, name="profile_student"),
    path('profile_student_save', views_student.profile_student_save, name="profile_student_save"),
    path('student_save_fcmtoken',
         views_student.student_save_fcmtoken, name="student_save_fcmtoken"),
    path('firebase-messaging-sw.js',views.show_firebase_js,name="show_firebase_js"),
    path('notifications',views_student.notifications,name="notifications"),
    path('result_student',views_student.result_student,name="result_student"),
    path('class_room_join/<int:subject_id>/<int:session_year_id>',
         views_student.class_room_join,name="class_room_join"),
    path('node_modules/canvas-designer/widget.html',
         views_staff.return_html_widget,name="return_html_widget"),
    path('testurl/',views.test_url)
]+static(settings.MEDIA_URL,
         document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL,
                                                   document_root=settings.STATIC_ROOT)
