# Generated by Django 4.2.4 on 2023-08-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0002_rename_profile_image_modelstudents_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelstaff',
            old_name='address',
            new_name='address_text',
        ),
    ]
